name: Tests
on:
  push:
    branches:
      - master
      - integration-tests
jobs:
  backend-unit:
    runs-on: ubuntu-latest

    env:
      REPO: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
      BRANCH: "${{github.ref_name}}"

    steps:
      - name: Echo variables
        run: |
          echo "repository url: $REPO"
          echo "deployment branch: $BRANCH"

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Setup repository
        run: |
          git clone $REPO .
          git checkout $BRANCH

      - name: Build
        working-directory: ./backend/
        run: |
          npm install
          npm run build

      - name: Run Tests via script
        working-directory: ./backend/
        run: "npm run test:unit"
